In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use('fivethirtyeight')
pd.set_option('display.max_columns', 500)
color_pal = plt.rcParams["axes.prop_cycle"].by_key()["color"]

In [6]:
BikeShareData_202304 = pd.read_csv('/Users/ericm/Documents/BikeShareData_20241111/202304-divvy-tripdata.csv')
BikeShareData_202305 = pd.read_csv('/Users/ericm/Documents/BikeShareData_20241111/202305-divvy-tripdata.csv')

In [8]:
BikeShareData_2023AprMay = pd.concat([BikeShareData_202304, BikeShareData_202305], ignore_index=True)
BikeShareData_2023AprMay

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,8FE8F7D9C10E88C7,electric_bike,2023-04-02 08:37:28,2023-04-02 08:41:37,NaN,NaN,NaN,NaN,41.800000,-87.600000,41.79,-87.60,member
1,34E4ED3ADF1D821B,electric_bike,2023-04-19 11:29:02,2023-04-19 11:52:12,NaN,NaN,NaN,NaN,41.870000,-87.650000,41.93,-87.68,member
2,5296BF07A2F77CB5,electric_bike,2023-04-19 08:41:22,2023-04-19 08:43:22,NaN,NaN,NaN,NaN,41.930000,-87.660000,41.93,-87.66,member
3,40759916B76D5D52,electric_bike,2023-04-19 13:31:30,2023-04-19 13:35:09,NaN,NaN,NaN,NaN,41.920000,-87.650000,41.91,-87.65,member
4,77A96F460101AC63,electric_bike,2023-04-19 12:05:36,2023-04-19 12:10:26,NaN,NaN,NaN,NaN,41.910000,-87.650000,41.91,-87.63,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1031412,48BDA26F34445546,electric_bike,2023-05-18 10:26:43,2023-05-18 10:48:00,Clark St & Elmdale Ave,KA1504000148,NaN,NaN,41.990876,-87.669721,42.00,-87.66,member
1031413,573025E5EDE10DE1,electric_bike,2023-05-17 14:32:48,2023-05-17 14:45:37,State St & 33rd St,13216,NaN,NaN,41.834734,-87.625798,41.83,-87.62,member
1031414,D88D48898C6FB63E,electric_bike,2023-05-17 07:59:29,2023-05-17 08:04:54,Columbus Dr & Randolph St,13263,NaN,NaN,41.884422,-87.619393,41.88,-87.63,member
1031415,4692DCD2F87497F5,electric_bike,2023-05-18 08:34:48,2023-05-18 08:38:40,Public Rack - Karlov Ave & Lawrence Ave,1127.0,NaN,NaN,41.970000,-87.730000,41.97,-87.74,member
1031416,6ACB7E383473D019,electric_bike,2023-05-29 21:16:58,2023-05-29 21:24:35,State St & 33rd St,13216,NaN,NaN,41.834715,-87.625764,41.84,-87.65,member

In [10]:
BikeShareData_2023AprMay['ride_id'].value_counts(

ride_id
8FE8F7D9C10E88C7    1
DBC67DEDFD01C785    1
F157273F4A83F0EC    1
7B6E13D12BE3DBC9    1
DD870EC9F5DE6ECC    1
                   ..
34B25E470E9B216B    1
843243DEB324AD7B    1
A554986088910FD1    1
34D507B2D9E5581C    1
6ACB7E383473D019    1
Name: count, Length: 1031417, dtype: int64

In [12]:
BikeShareData_2023AprMay.to_csv('BikeShareData_2023AprMay.csv', index=False)